### ISSUE TITLE
build.sh will not run on OSX 10.10 

### ISSUE THREAD

**Issue by bittebak** [glassfish/docker#3]
**Result**
build.sh: line 19: md5sum: command not found
MD5 for jdk-8u25-linux-x64.rpm does not match! Download again!

**Root cause**
The command md5sum is not available on OSX.
The alternative is md5 with the -r option.
The output of md5 -r <filename> is almost identical but it has one space less.

**Fix for OSX**

> MD5="$JAVA_PKG_MD5  $JAVA_PKG"
> MD5_CHECK="`md5sum $JAVA_PKG"'
> 
> MD5="$JAVA_PKG_MD5 $JAVA_PKG"
> MD5_CHECK="`md5 -r $JAVA_PKG`"

**Comment by brunoborges** [comment]
Hi @bittebak, thanks for highlighting this. Would you mind to provide a fix through a Pull Request?

**Comment by phillipross** [comment]
Hi @brunoborges...  I've provided a fix for this with pull request #4
